site_name: pycmdlineapp_groundwork
site_description: All the libraries and boilerplate needed to make convenient commandline applications in Python 3.8+.
strict: true
site_url: https://bnaard.github.io/pycmdlineapp-groundwork/

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: blue
    accent: blue
#  logo: 'logo-white.svg'
#  favicon: 'favicon.png'

repo_name: bnaard/pycmdlineapp-groundwork
repo_url: https://github.com/bnaard/pycmdlineapp-groundwork

nav:
- Overview: index.md
# - install.md
# - Usage:
#   - usage/models.md
# - Contributing: contributing.md
# - changelog.md

markdown_extensions:
- markdown_include.include:
    base_path: docs
- toc:
    permalink: 🔗
- pymdownx.highlight
- pymdownx.extra

plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
    - examples/*
    - requirements.txt
