name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}

    - run: |
        export PATH="$PATH:$PWD/.venv/bin"
        which mkdocs
        ./.venv/bin/mike deploy --push --update-aliases ${{ steps.get-latest-tag.outputs.tag }} latest
        ./.venv/bin/mike set-default --push latest

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site