name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install

    - name: Get Latest Release
      id: latest_version
      uses:  bnaard/pycmdlineapp-groundwork 

    - run: ./.venv/bin/mike deploy --push --update-aliases ${{ steps.latest_version.outputs.latest_tag }} latest
    - run: ./.venv/bin/mike set-default --push latest

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site